version: '{build}'
image: Ubuntu2004
environment:
  global:
    HAXELIB_ROOT: /home/appveyor/haxelib

install:
  - cd /home/appveyor
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install haxe tar gcc-7 g++-7 gcc-7-multilib g++-7-multilib -y
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install hscript
  - haxelib install newgrounds
  - haxelib install flixel-addons
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - cd /home/appveyor/projects/refunked-linux

build_script:
  - haxelib run lime build linux

after_build:
  - tar -cvf ReFunked-Linux.tar -C /home/appveyor/projects/refunked-linux/export/release/linux/bin .

artifacts:
- path: ReFunked-Linux.tar
  name: FNF ReFunked for Linux